### PR TITLE
Fix issues #2 and #3. Adjusting .gitignore for eclipse.

### PR DESCRIPTION
**Pull request by marekgr**

### CODE REVIEW

**Comment by shevek** [comment]
Looks excellent, thank you. For some reason I didn't get a github notification about this PR, so it languished for a few days - I found it because Maros told me you would be doing some work, and I came to check! Merging and releasing a snapshot now.

**Comment by shevek** [comment]
By the way, my typical full test build is `./gradlew clean build coberturaReport` - just in case you didn't spot the integrated coverage. :-)

**Comment by marekgr** [comment]
Thanks for merging. Next time I will let you know :)

**Comment by shevek** [comment]
Funny, I got a notification for Maros's PR, and for this reply, but I didn't get any note for #2, #3 or this original PR. Perhaps github was broken for a day. Anyway, the snapshot is now up, and I can do official releases whenever you like. Thank you very much indeed.

**Comment by marekgr** [comment]
Releasing a snapshot into mvn central was sth I forgot to ask.

**Comment by shevek** [comment]
It's in sonatype snapshots as of now. I'll put up a final release later today.

**Pull request merged**
